### ISSUE TITLE
Results

### ISSUE THREAD

**Issue by kittyBS** [dmitrymyl/ortho2align#7]
Hello,
Can you help understand the output files? What do the columns mean in the resulting tsv files? How can I capture matches between query-subject?
Thank you

**Comment by dmitrymyl** [comment]
Hello,

Please refer to [this paragraph](https://github.com/dmitrymyl/ortho2align?tab=readme-ov-file#input-and-output-files) in the README.

Regarding matches between query and subject:
1. `bestSignificant.subject_orthologs.bed` has coordinates of subject orthologs with names as IDs of your query genes (since it doesn't know anything about the annotation of query species genes).
2. `annotation_files/bestSignificant.annotation.tsv` is meaningful if you also add a subject species annotation file (i.e., with gene coordinates in the subject species) -- it will match query IDs (that are the same for query and subject orthologs) with IDs of the subject species genes based on overlaps.
